name: CI2
on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
#     if: ${{ contains(github.event.head_commit.message, 'run_ci') }}
    strategy:
      matrix:
        version:
          - '1.7' # LTS
        os:
          - ubuntu-latest
          # - macOS-latest
          # - windows-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.SSH_SECRET }}
      - name: Clone Mehrotra.jl
        run: git clone https://github.com/simon-lc/Mehrotra.jl
      - name: Install private repo
        run: julia --project -e 'using Pkg; Pkg.add(; url="Mehrotra.jl")'
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
    
    
#       - uses: actions/checkout@v2
#       - uses: julia-actions/setup-julia@latest
#         with:
#           version: ${{ matrix.version }}
#           arch: ${{ matrix.arch }}
      # - uses: julia-actions/julia-buildpkg@latest
#       - uses: julia-actions/julia-runtest@latest
#       - uses: julia-actions/julia-uploadcodecov@latest
#         env:
#           CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}






# name: CI
# on:
#   push:
#     branches: [main]
#   pull_request:
#     types: [opened, synchronize, reopened]
# jobs:
#   test:
#     name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
#     runs-on: ${{ matrix.os }}
#     strategy:
#       fail-fast: false
#       matrix:
#         include:
#           - version: '1'
#             os: ubuntu-latest
#             arch: x64
# #     steps:
#       - uses: actions/checkout@v2
#       - uses: julia-actions/setup-julia@v1
#         with:
#           version: ${{ matrix.version }}
#           arch: ${{ matrix.arch }}
#       - uses: webfactory/ssh-agent@v0.5.4
#         with:
#             ssh-private-key: ${{ secrets.SSH_SECRET }}
#       - name: Clone Games.jl
#         run: git clone https://github.com/davide-f/{MyPrivateRepo}.jl
#       - name: Install private repo
#         run: julia --project -e 'using Pkg; Pkg.add(; url="{MyPrivateRepo}.jl")'
#       - uses: actions/cache@v1
#         env:
#           cache-name: cache-artifacts
#         with:
#           path: ~/.julia/artifacts
#           key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
#           restore-keys: |
#             ${{ runner.os }}-test-${{ env.cache-name }}-
#             ${{ runner.os }}-test-
#             ${{ runner.os }}-
#       - uses: julia-actions/julia-buildpkg@v1
#       - uses: julia-actions/julia-runtest@v1
